// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrowthTracker.Repositories.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public int? AccountId { get; set; }

    public DateTime? OrderDate { get; set; }

    public string CustomerName { get; set; }

    public string CustomerEmail { get; set; }

    public string ShippingAddress { get; set; }

    public string BillingAddress { get; set; }

    public decimal? OrderTotal { get; set; }

    public string OrderStatus { get; set; }

    public string PaymentMethod { get; set; }

    public string PaymentStatus { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}